/* Generated by Together */

package com.yonglilian.flowengine.runtime;

public class FlowPackage {
	private String ID;

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}
}